
// Lavino site behaviour (generated by build_site.py)
(function(){
  function getLang(){
    // 新闻详情页：每个语种一个独立 URL，以页面自身语言为准
    if(window.LAVINO_PAGE_LANG) return window.LAVINO_PAGE_LANG;
    try{
      var p = new URLSearchParams(location.search).get('lang');
      if(p) return p;
      var s = localStorage.getItem('lavino_lang');
      if(s) return s;
    }catch(e){}
    return 'en';
  }
  function applyLang(lang){
    if(!window.LAVINO_I18N) return;
    var D = window.LAVINO_I18N;
    document.documentElement.lang = lang;
    // 同步 canonical / og:url：让每种语言指向它自己的版本，
    // 与页面里的 hreflang 声明保持一致（否则谷歌会认为四个语言是同一个页面而忽略声明）。
    (function(){
      var clean = location.origin + location.pathname;
      var selfUrl = (lang === 'en') ? clean : clean + '?lang=' + lang;
      var c = document.querySelectorAll('link[rel="canonical"]')[0];
      if(c) c.setAttribute('href', selfUrl);
      var o = document.querySelectorAll('meta[property="og:url"]')[0];
      if(o) o.setAttribute('content', selfUrl);
    })();
    // 取值：本语言没填（null 或空字符串）就用英文兜底 ——
    // 这样管理端里西语/俄语留空时，网站上不会出现一片空白。
    function pick(k){
      if(!D[k]) return null;
      var v = D[k][lang];
      if(v == null || v === ''){ v = D[k].en; }
      return (v == null) ? null : v;
    }
    document.querySelectorAll('[data-i18n]').forEach(function(el){
      var v = pick(el.getAttribute('data-i18n'));
      if(v != null){
        // Rich-text keys (contain HTML like <strong>) render via innerHTML; plain keys stay textContent (safe).
        if(String(v).indexOf('<') !== -1){ el.innerHTML = v; }
        else{ el.textContent = v; }
      }
    });
    document.querySelectorAll('[data-i18n-attr]').forEach(function(el){
      var spec = el.getAttribute('data-i18n-attr').split(',');
      spec.forEach(function(part){
        var a = part.split(':');
        if(a.length!==2) return;
        var v = pick(a[1]);
        if(v != null) el.setAttribute(a[0], v);
      });
    });
    document.querySelectorAll('.lang-btn').forEach(function(b){
      b.classList.toggle('active', b.getAttribute('data-lang')===lang);
    });
    // 新闻列表页：卡片链接按当前语言指向对应语种的独立详情页
    document.querySelectorAll('[data-news-slug]').forEach(function(a){
      var s = a.getAttribute('data-news-slug');
      a.setAttribute('href', 'news/' + s + (lang === 'en' ? '' : '.' + lang) + '.html');
    });
    // WhatsApp：链接带上当前语言的预填话术（客户点开就只差按发送，不必先加联系人）
    var waNum = (window.LAVINO_COMPANY && window.LAVINO_COMPANY.whatsapp_url) || '';
    document.querySelectorAll('[data-wa-text]').forEach(function(a){
      var k = a.getAttribute('data-wa-text');
      if(waNum && D[k] && D[k][lang] != null){
        a.setAttribute('href', 'https://wa.me/' + waNum + '?text=' + encodeURIComponent(D[k][lang]));
      }
    });
    // 二维码同步换成对应语种（内含同一段预填话术）
    document.querySelectorAll('[data-wa-qr]').forEach(function(im){
      im.setAttribute('src', 'assets/web/wa-qr-' + lang + '.png');
    });
    try{ localStorage.setItem('lavino_lang', lang); }catch(e){}
    try{
      // 详情页每个语种是独立 URL，不要把 ?lang= 写进地址（避免影响 canonical）
      if(!window.LAVINO_PAGE_LANG){
        var url = new URL(location.href);
        url.searchParams.set('lang', lang);
        history.replaceState(null, '', url);
      }
    }catch(e){}
  }
  document.addEventListener('DOMContentLoaded', function(){
    var lang = getLang();
    applyLang(lang);
    document.querySelectorAll('.lang-btn').forEach(function(b){
      b.addEventListener('click', function(){
        var l = b.getAttribute('data-lang');
        // 新闻详情页：跳转到该语种的独立 URL；其余页面：原地切换（与原行为完全一致）
        if(window.LAVINO_NEWS_LANGMAP && window.LAVINO_NEWS_LANGMAP[l]){
          location.href = window.LAVINO_NEWS_LANGMAP[l]; return;
        }
        applyLang(l);
      });
    });
    var y = document.getElementById('year');
    if(y) y.textContent = new Date().getFullYear();
    var form = document.getElementById('contactForm');
    if(form){
      var okBox = document.getElementById('formOk');
      var warnBox = document.getElementById('formWarn');
      var failBox = document.getElementById('formFail');
      function show(box){
        if(okBox) okBox.style.display = (box === okBox) ? 'block' : 'none';
        if(warnBox) warnBox.style.display = (box === warnBox) ? 'block' : 'none';
        if(failBox) failBox.style.display = (box === failBox) ? 'block' : 'none';
      }
      // 无 JS 兜底回到本页时带 ?sent=1（表单转发服务提交成功后跳回），视为发送成功
      if(/[?&]sent=1/.test(location.search)) show(okBox);

      var submitBtn = form.querySelector('button[type="submit"]');
      function t(key){
        var D = window.LAVINO_I18N;
        if(D && D[key] && D[key][getLang()] != null) return D[key][getLang()];
        return '';
      }

      form.addEventListener('submit', function(e){
        var f = form.elements;
        var name = (f['name'] && f['name'].value) || '';
        var company = (f['company'] && f['company'].value) || '';
        var email = (f['email'] && f['email'].value) || '';
        var country = (f['country'] && f['country'].value) || '';
        if(!name || !email){ e.preventDefault(); show(warnBox); return; }

        // 主题写清楚，收件箱里一眼能认出是谁、哪个国家（转发服务的 _subject 字段）
        var subj = document.getElementById('formSubject');
        if(subj){
          subj.value = 'Website inquiry — ' + name +
            (company ? ' · ' + company : '') + (country ? ' · ' + country : '');
        }
        // 没有配 AJAX 地址就交给浏览器原生 POST（保证留言一定发得出去）
        var ajaxUrl = (window.LAVINO_COMPANY && window.LAVINO_COMPANY.form_ajax) || '';
        if(!ajaxUrl || !window.fetch) return;

        e.preventDefault();
        show(null);
        var btnLabel = submitBtn ? submitBtn.textContent : '';
        if(submitBtn){ submitBtn.disabled = true; submitBtn.textContent = t('form_sending') || btnLabel; }
        fetch(ajaxUrl, { method: 'POST', body: new FormData(form), headers: { 'Accept': 'application/json' } })
          .then(function(r){ if(!r.ok) throw new Error('HTTP ' + r.status); return r.json(); })
          .then(function(d){
            if(String(d && d.success) !== 'true') throw new Error('rejected');
            form.reset();
            show(okBox);
          })
          .catch(function(){ show(failBox); })   // 失败绝不谎报成功，直接给 WhatsApp / 邮箱兜底
          .then(function(){ if(submitBtn){ submitBtn.disabled = false; submitBtn.textContent = btnLabel; } });
      });
    }
  });
})();
